import type { NextPage } from 'next'
import Head from 'next/head'
// Components
import {
  Services,
  Testimonials,
  PricingPlans,
  Cta,
  RecentPosts,
} from '@/components/home'
import Footer from '@/components/layouts/Footer/Footer'
// Styles
import styles from '../styles/pages/Home.module.scss'
import React from 'react'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Services />
        <Testimonials testimonials={[]} />
        <PricingPlans />
        <RecentPosts />
        <Cta />
      </main>
      <Footer />
    </>
  )
}

export default Home
