import React, { ReactElement } from 'react'
import Head from 'next/head'
// Components
import {
  Services,
  Testimonials,
  PricingPlans,
  Cta,
  RecentArticles,
  Pharmacies,
} from '@/components/home'
// Styles
import { MainLayout } from '@/components/layouts'
import testimonials from './../data/testimonials'

const Home = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Testimonials testimonials={testimonials} />
      <PricingPlans />
      <RecentArticles />
      <Cta />
    </>
  )
}

Home.getLayout = function getLayout(page: ReactElement) {
  return <MainLayout>{page}</MainLayout>
}

export default Home
